export {default as timeline } from './TimeLiness.vue'
export {default as calendar } from './CalenDarss.vue'
export {default as welcome } from './WelComess.vue'
export {default as carousel } from './CarouSelss.vue'
export {default as imgs } from './ImgSss.vue'
export {default as KonList } from './KonList.vue'